apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-config
  namespace: csas-argocd-sys
spec:
  destination:
    namespace: csas-argocd-sys
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
      values: |
        cloud_config: |
          {{- .Values.cloud_config | nindent 10 }}
    path: .
    repoURL: 'https://github.com/mrysavy/test-config.git'
    targetRevision: HEAD
